### ISSUE TITLE
SDL2 include/library path from pkg-config not used

### ISSUE THREAD

**Issue by jamer** [gosu/gosu#283]
When building libgosu, although SDL2's pkg-config is queried for existence, the build data recommended by pkg-config is not used.  (Note that the recommendations for vorbisfile are used, so SDL2 being left out is inconsistent.)

When compiling libgosu, if SDL2 is in a non-default place, the following compile error occurs:

```
[ 28%] Building CXX object CMakeFiles/GosuStatic.dir/Users/user/Source/gosu/src/Graphics/Resolution.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++0x -g -g -Wall -Wextra -pedantic -I/Users/user/Source/gosu/cmake/.. -I/Users/user/Library/Homebrew/Cellar/libvorbis/1.3.5/include -I/Users/user/Library/Homebrew/Cellar/libogg/1.3.2/include    -o CMakeFiles/GosuStatic.dir/Users/user/Source/gosu/src/Graphics/Resolution.cpp.o -c /Users/user/Source/gosu/src/Graphics/Resolution.cpp
/Users/user/Source/gosu/src/Graphics/Resolution.cpp:49:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/GosuStatic.dir/Users/user/Source/gosu/src/Graphics/Resolution.cpp.o] Error 1
make[1]: *** [CMakeFiles/GosuStatic.dir/all] Error 2
make: *** [all] Error 2
```

## Possible solution

I was able to get a working build by adding SDL2_INCLUDEDIR to src.cmake's INCLUDE_DIRECTORIES block and adding SDL2_LIBRARIES to GosuConfig.cmake.in's LINK_LIBRARIES block.

Although I'm not very familiar with CMake and I'm not sure if that's the "right" way to solve this issue, so I am leaving this as a bug report for review.

**Comment by jlnr** [comment]
Ahhh CMake. I have a bunch of git stashes and To Do items because I've been meaning to completely rewrite the CMake files, but it just never really works. The more I work with it, the less sense it makes. I'll give it another try today.

**Comment by jlnr** [comment]
I think this has been fixed in git HEAD. I can now build & install Gosu on OS X 10.10 and Ubuntu 15.04. Thanks for nudging me once again to fix this mess :)

**Comment by PaulUdacity** [comment]
Nice refactoring, @jlnr! However, I still get the error on Mac OS X 10.10.4 when Homebrew is installed in a location other than /usr/local.

Notice that libogg and libvorbis are included via `-I` but that SDL2 is not. This means that the CFLAGS from SDL2 are not being used.

```
$ pkg-config --cflags sdl2
-D_THREAD_SAFE -I/Users/user/homebrew/include/SDL2 
```

## Steps to reproduce

1. mkdir scratch; cd scratch
2. git clone https://github.com/Homebrew/homebrew.git
3. PATH=$PWD/homebrew/bin:/usr/bin:/bin
4. brew install cmake pkg-config sdl2 libogg libvorbis
5. git clone https://github.com/gosu/gosu.git
6. mkdir gosu/cmake/build; cd gosu/cmake/build
7. cmake .. && VERBOSE=1 make

## Error

```
[ 27%] Building CXX object CMakeFiles/gosu.dir/Users/user/gosu/src/Graphics/Resolution.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Dgosu_EXPORTS -std=c++0x -fPIC -I/Users/user/gosu/cmake/.. -I/Users/user/homebrew/Cellar/libvorbis/1.3.5/include -I/Users/user/homebrew/Cellar/libogg/1.3.2/include    -DGOSU_SHARED_EXPORTS -o CMakeFiles/gosu.dir/Users/user/gosu/src/Graphics/Resolution.cpp.o -c /Users/user/gosu/src/Graphics/Resolution.cpp
/Users/user/gosu/src/Graphics/Resolution.cpp:49:10: fatal error: 'SDL2/SDL.h'
      file not found
#include <SDL2/SDL.h>
         ^
1 error generated.
```

## Expected result

Build succeeds without error.

**Comment by jamer** [comment]
Nice refactoring, @jlnr! However, I still get the error on Mac OS X 10.10.4 when Homebrew is installed in a location other than /usr/local.

Notice that libogg and libvorbis are included via `-I` but that SDL2 is not. This means that the CFLAGS from SDL2 are not being used.

```
$ pkg-config --cflags sdl2
-D_THREAD_SAFE -I/Users/user/homebrew/include/SDL2 
```

## Steps to reproduce

1. mkdir scratch; cd scratch
2. git clone https://github.com/Homebrew/homebrew.git
3. PATH=$PWD/homebrew/bin:/usr/bin:/bin
4. brew install cmake pkg-config sdl2 libogg libvorbis
5. git clone https://github.com/gosu/gosu.git
6. mkdir gosu/cmake/build; cd gosu/cmake/build
7. cmake .. && VERBOSE=1 make

## Error

```
[ 27%] Building CXX object CMakeFiles/gosu.dir/Users/user/gosu/src/Graphics/Resolution.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Dgosu_EXPORTS -std=c++0x -fPIC -I/Users/user/gosu/cmake/.. -I/Users/user/homebrew/Cellar/libvorbis/1.3.5/include -I/Users/user/homebrew/Cellar/libogg/1.3.2/include    -DGOSU_SHARED_EXPORTS -o CMakeFiles/gosu.dir/Users/user/gosu/src/Graphics/Resolution.cpp.o -c /Users/user/gosu/src/Graphics/Resolution.cpp
/Users/user/gosu/src/Graphics/Resolution.cpp:49:10: fatal error: 'SDL2/SDL.h'
      file not found
#include <SDL2/SDL.h>
         ^
1 error generated.
```

## Expected result

Build succeeds without error.

**Comment by jlnr** [comment]
Ah, thanks for the detailed instructions, that made it easy to reproduce the issue locally.

The include directory is supposed to be set here, I'll dig into why it isn't happening:

https://github.com/gosu/gosu/blob/ed255804e0fb0f5745f60d598b7adb671d884345/cmake/Compilation.cmake#L135

**Comment by jlnr** [comment]
The first issue was that the `S` was missing, ouch – `SDL2_INCLUDE_DIRS` is the right variable.

The second issue is that `SDL2_INCLUDE_DIRS` returns the `SDL2` folder, and Gosu does `#include <SDL2/sdl.h>`, not `<sdl.h>`. I remember reading that `<sdl.h>` is the proper way to include SDL headers. I'll better start doing that now, even if it means refactoring the Ruby gem to do the right thing.

**Comment by jlnr** [comment]
The third issue is that `SDL2_INCLUDE_DIRS` was not added to the linker path.

The fourth issue is that GosuConfig sets `GOSU_LIBRARY` to just "gosu", not a full file path.

And lastly, the generated `gosu.dylib` didn't have the correct dylib install name if it wasn't in one of the default directories (/lib, /usr/lib or /usr/local/lib).

I hope this fixes all these issues for you :) I successfully built and installed Gosu from inside `scratch`, and then built and ran the examples.

**Comment by jamer** [comment]
This fixes the issue for me. Thanks! :)
